name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      TARGET_PATH: "/var/www/html/test2/"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Test SSH Connection
        run: |
         sshpass -p "your_server_password" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null your_server_user@your_server_ip "echo 'SSH connection successful'"
          
