name: Copy Files to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      TARGET_PATH: "/var/www/html/pramesh/"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy Files to Remote Server
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ "$SERVER_USER@$SERVER_IP:$TARGET_PATH"
      
      - name: Restart Apache on Remote Server
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -t -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "echo '$SERVER_PASSWORD' | sudo -S systemctl restart apache2"
